dapricot/accounts/urls.py
""" Django Apricot Accounts urls module
"""
from django.urls.conf import path, re_path
from django.conf import settings

from dacommon.views import MessageView
from dapricot.accounts.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetConfirmView,
    ActivateView,
    SignupView,
    AccountView,
)

app_name = "daaccounts"

urlpatterns = [
    path("", AccountView.as_view(), name="account"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password_change/", PasswordChangeView.as_view(), name="password_change"),
    path(
        "password_change/done/",
        MessageView.as_view(
            message_title="Password change",
            message="Password change successful",
        ),
        name="password_change_done",
    ),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_confirm/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/done/",
        MessageView.as_view(
            message_title="Password reset",
            message=(
                "We’ve emailed you instructions for setting your password, "
                "if an account exists with the email you entered. You should receive them shortly.",
                "If you don’t receive an email, please make sure you’ve entered the address you registered with, "
                "and check your spam folder.",
            ),
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        MessageView.as_view(
            message_title="Password reset complete",
            message="Your password has been set. You may go ahead and log in now.",
        ),
        name="password_reset_complete",
    ),
    path(
        "account_activation_sent/",
        MessageView.as_view(
            template_name="dapricot/accounts/account_activation_sent.html",
            message=(
                MessageView.MessageType.INFO,
                "Your activation link has been sent.",
            ),
        ),
        name="account_activation_sent",
    ),
    re_path(
        r"activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,6}-[0-9A-Za-z]{1,32})/",
        ActivateView.as_view(),
        name="activate",
    ),
]

if settings.AUTO_SIGNUP_ENABLED:
    urlpatterns += [
        path("signup/", SignupView.as_view(), name="signup"),
    ]

elif settings.ACCOUNTS_REQUESTS_ENABLED:
    urlpatterns += [
        path("signup/", SignupView.as_view(), name="account_request"),
        re_path(
            r"signup/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,6}-[0-9A-Za-z]{1,32})/",
            SignupView.as_view(),
            name="signup",
        ),
    ]

dapricot/accounts/models.py
""" Django Apricot Accounts models module
"""
from django.db import models
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.urls.base import reverse
from django.conf import settings

from dapricot.accounts.tokens import signup_token, account_activation_token
from dapricot.accounts.managers import UserManager


class User(AbstractUser):
    """User model"""

    USERNAME_FIELD = settings.AUTH_USERNAME_FIELD
    REQUIRED_FIELDS = (
        [
            "email",
        ]
        if settings.AUTH_USERNAME_FIELD == "username"
        else [
            "username",
        ]
    )
    email = models.EmailField(_("email address"), blank=True, unique=True)
    email_confirmed = models.BooleanField(default=False)

    objects = UserManager()

    class Meta:
        db_table = "dapricot_user"
        verbose_name = "user"
        verbose_name_plural = "users"

    def __str__(self):
        return f"{self.username}"

    def get_account_activation_link(self):
        """Returns the signup url"""
        if not self.email_confirmed:
            kwargs = {
                "uid": urlsafe_base64_encode(force_bytes(self.pk)),
                "token": account_activation_token.make_token(self),
            }

            return reverse("daaccounts:activate", kwargs=kwargs)

        return None


class AccountRequest(models.Model):
    """New account request model"""

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        validators=[username_validator],
        blank=True,
    )
    request_date = models.DateTimeField(
        _("request_date"), auto_now_add=True, editable=False
    )
    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True, blank=True)

    class Meta:
        db_table = "dapricot_account_request"
        verbose_name = "account request"
        verbose_name_plural = "account requests"

    def __str__(self):
        return f"{self.username}"

    def get_account_creation_link(self):
        """Returns the signup url"""
        kwargs = {
            "uidb64": urlsafe_base64_encode(force_bytes(self.pk)),
            "token": signup_token.make_token(self),
        }

        return reverse("daaccounts:signup", kwargs=kwargs)

dapricot/accounts/forms.py
""" Django Apricot Accounts forms module
"""
from django import forms
from django.forms.models import ModelFormOptions
from django.contrib.auth.forms import UserCreationForm

from dapricot.accounts.models import AccountRequest, User


class SignUpForm(UserCreationForm):
    """Signup form"""

    email = forms.EmailField(
        max_length=254, help_text="Required. Inform a valid email address."
    )

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )


class RequestedSignUpForm(UserCreationForm):
    """Signup form"""

    # TO DO: change username to a dropdown for alternate options.(add alternate option to AccountRequest model)
    email = forms.EmailField(
        max_length=254,
        help_text="Required. Inform a valid email address.",
        widget=forms.TextInput(attrs={"readonly": "readonly"}),
    )
    username = forms.CharField(
        max_length=150,
        help_text="Required. Inform a valid username.",
        widget=forms.TextInput(attrs={"readonly": "readonly"}),
    )

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )


class RequestUserCreationForm(forms.ModelForm):
    """User request form"""

    class Meta:
        model = AccountRequest
        fields = ("first_name", "last_name", "email")

    def get_available_username(self):
        """gets a valid username for the requester"""
        model = ModelFormOptions(getattr(RequestUserCreationForm, "Meta", None)).model
        username = (
            f"{self.cleaned_data['first_name'][:3]}{self.cleaned_data['last_name'][:3]}"
        )

        for similar_username in (
            model.objects.filter(username__contains=username),
            User.objects.filter(username__contains=username),
        ):
            try:
                similar_username = model.objects.filter(username__contains=username)
                if similar_username.count() > 0:
                    username_complement = similar_username.last().username.split(
                        username
                    )[-1]
                    username_complement = (
                        int(username_complement if username_complement != "" else "1")
                        + 1
                    )
                    username = f"{username}{username_complement}"
                    break
            except model.DoesNotExist:
                pass

        return username

    def save(self, commit=True):
        request = super().save(commit=False)
        request.username = self.get_available_username()
        if commit:
            request.save()
        return request

dapricot/accounts/views.py
""" Django Apricot Accounts views module
"""
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth import login, get_user_model, views, logout
from django.shortcuts import render, redirect
from django.urls.base import reverse_lazy
from django.conf import settings
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from dacommon.views import BaseView, DjangoStyleOverrideMixin, MessageView
from dapricot.accounts.forms import (
    SignUpForm,
    RequestedSignUpForm,
    RequestUserCreationForm,
)
from dapricot.accounts.tokens import account_activation_token, signup_token
from dapricot.accounts.models import AccountRequest

__all__ = [
    "PasswordResetConfirmView",
    "PasswordResetView",
    "LogoutView",
    "PasswordChangeView",
    "LoginView",
    "SignupView",
    "ActivateView",
]


class AccountView(BaseView):
    """Account dashboard view"""

    template_name = "dapricot/accounts/account.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PasswordResetView(DjangoStyleOverrideMixin, views.PasswordResetView):
    """Password Reset View"""

    template_name = "dapricot/accounts/password_reset_form.html"
    email_template_name = "dapricot/accounts/password_reset_email.html"
    success_url = reverse_lazy("daaccounts:password_reset_done")


class PasswordResetConfirmView(
    DjangoStyleOverrideMixin, views.PasswordResetConfirmView
):
    """Password Reset Confirm View"""

    template_name = "dapricot/accounts/password_reset_confirm.html"
    success_url = reverse_lazy("daaccounts:password_reset_complete")


class LogoutView(MessageView):
    """Password Reset View"""

    message = "Logged out"

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class PasswordChangeView(DjangoStyleOverrideMixin, views.PasswordChangeView):
    """Password Reset View"""

    template_name = "dapricot/accounts/password_change_form.html"
    success_url = reverse_lazy("daaccounts:password_change_done")


class LoginView(DjangoStyleOverrideMixin, views.LoginView):
    """Password Reset View"""

    template_name = "dapricot/accounts/login.html"
    redirect_authenticated_user = True


class SignupView(BaseView):
    """Signup view"""

    template_name = "dapricot/accounts/signup.html"

    def post(self, request, *args, **kwargs):
        """Post request"""
        form = None
        if settings.AUTO_SIGNUP_ENABLED:
            form = SignUpForm(request.POST)
        elif "uidb64" in kwargs:
            uid = urlsafe_base64_decode(kwargs["uidb64"])
            account_request = AccountRequest.objects.get(pk=uid)
            if signup_token.check_token(account_request, kwargs["token"]):
                form = RequestedSignUpForm(request.POST)
        elif settings.ACCOUNTS_REQUESTS_ENABLED:
            form = RequestUserCreationForm(request.POST)

        self.template_variables["form"] = form

        if form is not None:
            if form.is_valid():
                if isinstance(form, RequestUserCreationForm):
                    form.save()

                    return redirect(settings.SIGNUP_REDIRECT_URL)

                user = form.save(commit=False)
                user.is_active = False
                user.save()

                current_site = get_current_site(request)
                subject = "Activate Your MySite Account"
                message = render_to_string(
                    "dapricot/accounts/account_activation_email.html",
                    {
                        "user": user,
                        "domain": current_site.domain,
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "token": account_activation_token.make_token(user),
                    },
                )
                user.email_user(subject, message)
                if (
                    settings.ACCOUNTS_REQUESTS_ENABLED
                    and not settings.AUTO_SIGNUP_ENABLED
                    and signup_token.check_token(account_request, kwargs["token"])
                ):
                    # TO DO: change delete for 'is_active' field
                    account_request.delete()

                return redirect("daaccounts:account_activation_sent")

            return render(request, self.template_name, self.template_variables)
        # TO DO: change last redirect for an error page
        return redirect("daaccounts:signup")

    def get(self, request, *args, **kwargs):
        """Get request"""
        if request.user.is_authenticated and not request.user.is_staff:
            return redirect("home")

        if settings.AUTO_SIGNUP_ENABLED:
            form = SignUpForm()
        elif settings.ACCOUNTS_REQUESTS_ENABLED:
            form = RequestUserCreationForm()
            if "uidb64" in kwargs:
                uid = urlsafe_base64_decode(kwargs["uidb64"])
                account_request = AccountRequest.objects.get(pk=uid)
                if signup_token.check_token(account_request, kwargs["token"]):
                    data = {
                        "username": account_request.username,
                        "email": account_request.email,
                    }
                    form = RequestedSignUpForm(initial=data)
                else:
                    return redirect("daaccounts:account_request")

        self.template_variables["form"] = form
        return super().get(request)


class ActivateView(BaseView):
    """Signup view"""

    template_name = "account_activation_invalid.html"

    def get(self, request, uidb64, token):
        """Get request"""
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = get_user_model().objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.email_confirmed = True
            user.save()
            login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().get(request)

dapricot/templates/dapricot/accounts/account.html
{% extends 'dapricot/base.html' %}
{% load daaccounts_tags %}

{% block header %}
{% user_menu %}
{% endblock %}

{% block main %}
<article class="grid-main">
	<div class="container">
		<div class="box card-primary half-center autoheight">
			<h3>Security</h3>
		</div>
		<div class="box card half-center autoheight">
			<p>
				<a href="{% url 'daaccounts:password_change' %}" class="icon-key">Change password</a>
			</p>
		</div>
		<div class="box card-primary half-center autoheight">
			<h3>Integrations</h3>
		</div>
		<div class="box card half-center autoheight">
			<div class="box half autoheight">
				{% if "dapricot.music" in installed_apps %}
				{% load damusic %}
				{% spotify_badge %}
				{% endif %}
			</div>
			<div class="box half autoheight">
				{% if "dafitness" in installed_apps %}
				{% load dafitness %}
				{% strava_badge %}
				{% endif %}
			</div>
		</div>
	</div>
</article>

{% endblock %}

dapricot/templates/dapricot/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'daaccounts:activate' uidb64=uid token=token %}
{% endautoescape %}

dapricot/templates/dapricot/accounts/login.html
{% extends 'dapricot/base.html' %}

{% block header %}
{% endblock %}

{% block main %}
<article class="grid-main">
	<div class="container">
		<div class="box card-primary half-center autoheight">
			<h2 class="icon-login">Login</h2>
		</div>
		<form method="post">
			<div class="box card half-center autoheight">
				{% csrf_token %}
				{% for field in form %}
				<div class="box half autoheight">
			    {{ field.label_tag }} {{ field }}
			    {% if field.help_text %}
			    <small style="color: grey">{{ field.help_text }}</small>
			    {% endif %}
			    {% for error in field.errors %}
			    <p class="error">{{ error }}</p>
			    {% endfor %}
			    </p>
				</div>
				{% endfor %}
				</div>
		  	</div>
			<div class="box card half-center autoheight">
			  	<a href="{% url 'daaccounts:password_reset' %}" class="button">Forgot password?</a>
			  	<button type="submit" class="button-primary">Login</button>
		  	</div>
		</form>
	</div>
</article>
{% endblock %}

dapricot/templates/dapricot/accounts/password_change_form.html
{% extends 'dapricot/base.html' %}
{% load i18n static %}
{% block header %}
{% endblock %}

{% block main %}
<article class="grid-main">
	<div class="container">
		<div class="box card-primary half-center autoheight">
			<h2>Password change</h2>
			<p>{% translate 'Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly.' %}</p>
		</div>
		
		<form method="post">
		<div class="box card half-center autoheight">
		{% csrf_token %}
		{% if form.errors %}
			<div class="box full autoheight error">
		    {% blocktranslate count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktranslate %}
		    </div>
		{% endif %}			
			<div class="box full autoheight error">{{ form.old_password.errors }}</div>
		    <div class="box half autoheight">{{ form.old_password.label_tag }} {{ form.old_password }}</div>
			<div class="box full autoheight error">
				{{ form.new_password1.errors }}</br>
				{{ form.new_password2.errors }}
			</div>
		    <div class="box half autoheight">
		    	{{ form.new_password1.label_tag }} {{ form.new_password1 }} </br>
		    	{{ form.new_password2.label_tag }} {{ form.new_password2 }}
		    </div>
		    <div class="box half autoheight">
		    {% if form.new_password1.help_text %}
		    <div class="help"{% if form.new_password1.id_for_label %} id="{{ form.new_password1.id_for_label }}_helptext"{% endif %}>{{ form.new_password1.help_text|safe }}</div>
		    {% endif %}
		    {% if form.new_password2.help_text %}
		    <div class="help"{% if form.new_password2.id_for_label %} id="{{ form.new_password2.id_for_label }}_helptext"{% endif %}>{{ form.new_password2.help_text|safe }}</div>
		    {% endif %}
			</div>
		</div>
		<div class="box card half-center autoheight">
		    <input type="submit" class="button-primary" value="{% translate 'Change my password' %}" class="default">
	    </div>
		</form>
{% endblock %}

dapricot/templates/dapricot/accounts/password_reset_confirm.html
{% extends 'dapricot/base.html' %}
{% load i18n static %}

{% block main %}

<article class="grid-main">
	<div class="container">
		<div class="box card-primary half-center autoheight">
			<h2>Password reset confirmation</h2>
			{% if validlink %}
			
			<p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
		</div>
			<form method="post">
			<div class="box card half-center autoheight">
				{% csrf_token %}
				<div class="box half autoheight">
			        {{ form.new_password1.errors }}
			        <label for="id_new_password1">{% translate 'New password:' %}</label>
			        {{ form.new_password1 }}
			    </div>
				<div class="box half autoheight">
			        {{ form.new_password2.errors }}
			        <label for="id_new_password2">{% translate 'Confirm password:' %}</label>
			        {{ form.new_password2 }}
			    </div>
			</div>
			
			    <input class="hidden" autocomplete="username" value="{{ form.user.get_username }}">
			<div class="box card half-center autoheight">
		    	<input type="submit" class="button-primary" value="{% translate 'Change my password' %}">
		    </div>
			</form>
			{% else %}
			<p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
			</div>
			{% endif %}
{% endblock %}

dapricot/templates/dapricot/accounts/password_reset_form.html
{% extends 'dapricot/base.html' %}
{% load i18n static %}

{% block main %}
<article class="grid-main">
	<div class="container">
		<div class="box card-primary half-center autoheight">
			<h2 class="icon-user-add">Password reset</h2>
			<p>{% translate 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}</p>
		</div>
		<form method="post">
			<div class="box card half-center autoheight">
				{% csrf_token %}
				
				<div class="box full autoheight">
			    {{ form.email.errors }}
			    </div>
				<div class="box half autoheight">
			    <label for="id_email">{% translate 'Email address:' %}</label>
			    </div>
				<div class="box half autoheight">
			    {{ form.email }}
			    </div>
	    	</div>
			<div class="box card half-center autoheight">
		    	<input type="submit" class="button-primary" value="{% translate 'Reset my password' %}">
		    </div>
		</form>
	</div>
</article>
{% endblock %}

dapricot/templates/dapricot/accounts/signup.html
{% extends 'dapricot/base.html' %}

{% block main %}
<article class="grid-main">
	<div class="container">
		<div class="box card-primary half-center autoheight">
			<h2 class="icon-user-add">Register</h2>
		</div>
		<form method="post">
			<div class="box card half-center autoheight">
				{% csrf_token %}
				{% for field in form %}
				<div class="box half autoheight">
			    {{ field.label_tag }} {{ field }}
			    </div>
			    <div class="box half autoheight">
			    {% if field.help_text %}
			    <p><br/></p>
			    <small style="color: grey">{{ field.help_text }}</small>
			    {% endif %}
			    </div>
			    <div class="box full autoheight">
			    {% for error in field.errors %}
			    <p class="error">{{ error }}</p>
			    {% endfor %}
			    </p>
			    </div>
				{% endfor %}
		  	</div>
			<div class="box card half-center autoheight">
				<a href="{% url 'daaccounts:login' %}"  class="button">Already have an account?</a>
				<button type="submit" class="button-primary">Register</button>
		  	</div>
		</form>
	</div>
</article>
{% endblock %}